name: CI-build-and-push-image-for-dotnetapp

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Login to Docker Hub  
        uses: docker/login-action@v2
        with:
          username: r.f.schram25@gmail.com
          password: m.yUx8k@@VYpwP8
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: robschram/citybuilder:latest

  deploy:
    needs: build
    runs-on: self-hosted  # This will run on your self-hosted runner
    steps:
      - name: Login to Docker Hub  
        uses: docker/login-action@v2
        with:
          username: r.f.schram25@gmail.com
          password: m.yUx8k@@VYpwP8
        
      - name: Pull latest Docker image
        run: docker pull robschram/citybuilder:latest

      - name: Stop and remove old Docker container (if exists)
        run: |
         docker stop citybuilder || true
         docker rm citybuilder || true
        shell: cmd



      - name: Run new Docker container
        run: |
          docker run -d --name citybuilder -p 8080:8080 robschram/citybuilder:latest
