name: Run tests and generate report

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore citybuilder-backend.sln

      - name: Build
        run: dotnet build citybuilder-backend.sln --configuration Release --no-restore

      - name: Run tests with code coverage
        run: dotnet test citybuilder-backend.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./test-results
        
      - name: Find code coverage file
        id: find_coverage
        run: echo "coverage_file=$(find ./test-results -name 'coverage.cobertura.xml')" >> $GITHUB_ENV

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ${{ env.coverage_file }}
          token: f7ee4fa2-5ca1-4182-8f38-b1ee4109b0d5
          fail_ci_if_error: true
