name: Run tests and generate report

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore citybuilder-backend.sln

      - name: Build
        run: dotnet build citybuilder-backend.sln --configuration Release --no-restore

      - name: Run tests for TestCityBuilder.dll
        run: |
          # Run tests for the specific test DLL (TestCityBuilder.dll)
          dotnet test ./TestCityBuilder/bin/Release/net8.0/TestCityBuilder.dll --configuration Release --no-build --results-directory ./test-results
