name: Run tests and generate report

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore citybuilder-backend/citybuilder-backend.sln

      - name: Build
        run: dotnet build citybuilder-backend/citybuilder-backend.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test citybuilder-backend/citybuilder-backend.sln --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./test-results
