name: Run tests and generate report

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore citybuilder-backend.sln

      - name: Build
        run: dotnet build citybuilder-backend.sln --configuration Release --no-restore

      - name: Run tests with code coverage
        run: |
          dotnet test citybuilder-backend.sln --configuration Release --no-build \
            /p:CollectCoverage=true \
            /p:CoverletOutput=./test-results/coverage/ \
            /p:CoverletOutputFormat=cobertura
          
      - name: Upload code coverage to GitHub
        uses: codecov/codecov-action@v3
        with:
          file: ./test-results/coverage/cobertura.xml
